module.exports = {
    apps: [
        {
            name: "monit_private_ips",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 0 node monitPrivateIPs.js"',
            out_file: "/data/will/binance_utils/monit-private-ips-out.log",
            error_file: "/data/will/binance_utils/monit-private-ips-error.log",
        },
        {
            name: "monit_okx_zoned_ticker",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 0 node monitOkxZoneDTicker.js"',
            out_file: "/data/will/binance_utils/monit-okx-zoned-ticker-out.log",
            error_file:
                "/data/will/binance_utils/monit-okx-zoned-ticker-error.log",
        },
        {
            name: "monit_okx_zoned_btceth_ticker",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 0 node monitOkxZoneDBTCETHTicker.js"',
            out_file:
                "/data/will/binance_utils/monit-okx-zoned-btceth-ticker-out.log",
            error_file:
                "/data/will/binance_utils/monit-okx-zoned-btceth-ticker-error.log",
        },
        {
            name: "stat_btech001",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account btech001"',
            out_file: "/data/will/bnmm/stat-btech001-out.log",
            error_file: "/data/will/bnmm/stat-btech001-error.log",
        },
        {
            name: "stat_btech002",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account btech002"',
            out_file: "/data/will/bnmm/stat-btech002-out.log",
            error_file: "/data/will/bnmm/stat-btech002-error.log",
        },
        {
            name: "stat_btech003",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account btech003"',
            out_file: "/data/will/bnmm/stat-btech003-out.log",
            error_file: "/data/will/bnmm/stat-btech003-error.log",
        },
        {
            name: "stat_btech004",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account btech004"',
            out_file: "/data/will/bnmm/stat-btech004-out.log",
            error_file: "/data/will/bnmm/stat-btech004-error.log",
        },
        {
            name: "stat_btech005",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account btech005"',
            out_file: "/data/will/bnmm/stat-btech005-out.log",
            error_file: "/data/will/bnmm/stat-btech005-error.log",
        },
        {
            name: "stat_elkdaphne1",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account elkdaphne1"',
            out_file: "/data/will/bnmm/stat-elkdaphne1-out.log",
            error_file: "/data/will/bnmm/stat-elkdaphne1-error.log",
        },
        {
            name: "stat_elkdaphne2",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account elkdaphne2"',
            out_file: "/data/will/bnmm/stat-elkdaphne2-out.log",
            error_file: "/data/will/bnmm/stat-elkdaphne2-error.log",
        },
        {
            name: "stat_elkdaphne3",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account elkdaphne3"',
            out_file: "/data/will/bnmm/stat-elkdaphne3-out.log",
            error_file: "/data/will/bnmm/stat-elkdaphne3-error.log",
        },
        {
            name: "stat_elkdaphne4",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account elkdaphne4"',
            out_file: "/data/will/bnmm/stat-elkdaphne4-out.log",
            error_file: "/data/will/bnmm/stat-elkdaphne4-error.log",
        },
        {
            name: "stat_ltp146",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp146"',
            out_file: "/data/will/bnmm/stat-ltp146-out.log",
            error_file: "/data/will/bnmm/stat-ltp146-error.log",
        },
        {
            name: "stat_ltp147",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp147"',
            out_file: "/data/will/bnmm/stat-ltp147-out.log",
            error_file: "/data/will/bnmm/stat-ltp147-error.log",
        },
        {
            name: "stat_ltp148",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp148"',
            out_file: "/data/will/bnmm/stat-ltp148-out.log",
            error_file: "/data/will/bnmm/stat-ltp148-error.log",
        },
        {
            name: "stat_ltp149",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp149"',
            out_file: "/data/will/bnmm/stat-ltp149-out.log",
            error_file: "/data/will/bnmm/stat-ltp149-error.log",
        },
        {
            name: "stat_ltp150",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp150"',
            out_file: "/data/will/bnmm/stat-ltp150-out.log",
            error_file: "/data/will/bnmm/stat-ltp150-error.log",
        },
        {
            name: "stat_ltp173",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp173"',
            out_file: "/data/will/bnmm/stat-ltp173-out.log",
            error_file: "/data/will/bnmm/stat-ltp173-error.log",
        },
        {
            name: "stat_ltp198",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp198"',
            out_file: "/data/will/bnmm/stat-ltp198-out.log",
            error_file: "/data/will/bnmm/stat-ltp198-error.log",
        },
        {
            name: "stat_ltp214",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp214"',
            out_file: "/data/will/bnmm/stat-ltp214-out.log",
            error_file: "/data/will/bnmm/stat-ltp214-error.log",
        },
        {
            name: "stat_ltp244",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp244"',
            out_file: "/data/will/bnmm/stat-ltp244-out.log",
            error_file: "/data/will/bnmm/stat-ltp244-error.log",
        },
        {
            name: "stat_ltp385",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node stat.js --account ltp385"',
            out_file: "/data/will/bnmm/stat-ltp385-out.log",
            error_file: "/data/will/bnmm/stat-ltp385-error.log",
        },
        {
            name: "stat_ltp146_spot",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node mgstat.js --account ltp146"',
            out_file: "/data/will/bnmm/stat-ltp146-spot-out.log",
            error_file: "/data/will/bnmm/stat-ltp146-spot-error.log",
        },
        {
            name: "stat_ltp173_spot",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 1 node mgstat.js --account ltp173"',
            out_file: "/data/will/bnmm/stat-ltp173-spot-out.log",
            error_file: "/data/will/bnmm/stat-ltp173-spot-error.log",
        },
        {},
        {
            name: "stat_fbg001",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account fbg001"',
            out_file: "/data/will/bnmm/stat-fbg001-out.log",
            error_file: "/data/will/bnmm/stat-fbg001-error.log",
        },
        {
            name: "stat_fbg002",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account fbg002"',
            out_file: "/data/will/bnmm/stat-fbg002-out.log",
            error_file: "/data/will/bnmm/stat-fbg002-error.log",
        },
        {
            name: "stat_fbg003",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account fbg003"',
            out_file: "/data/will/bnmm/stat-fbg003-out.log",
            error_file: "/data/will/bnmm/stat-fbg003-error.log",
        },
        {
            name: "stat_fbg004",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account fbg004"',
            out_file: "/data/will/bnmm/stat-fbg004-out.log",
            error_file: "/data/will/bnmm/stat-fbg004-error.log",
        },
        {
            name: "stat_trader1",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader1"',
            out_file: "/data/will/bnmm/stat-trader1-out.log",
            error_file: "/data/will/bnmm/stat-trader1-error.log",
        },
        {
            name: "stat_trader2",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader2"',
            out_file: "/data/will/bnmm/stat-trader2-out.log",
            error_file: "/data/will/bnmm/stat-trader2-error.log",
        },
        {
            name: "stat_trader3",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader3"',
            out_file: "/data/will/bnmm/stat-trader3-out.log",
            error_file: "/data/will/bnmm/stat-trader3-error.log",
        },
        {
            name: "stat_trader4",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader4"',
            out_file: "/data/will/bnmm/stat-trader4-out.log",
            error_file: "/data/will/bnmm/stat-trader4-error.log",
        },
        {
            name: "stat_trader6",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader6"',
            out_file: "/data/will/bnmm/stat-trader6-out.log",
            error_file: "/data/will/bnmm/stat-trader6-error.log",
        },
        {
            name: "stat_trader14",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader14"',
            out_file: "/data/will/bnmm/stat-trader14-out.log",
            error_file: "/data/will/bnmm/stat-trader14-error.log",
        },
        {
            name: "stat_trader15",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader15"',
            out_file: "/data/will/bnmm/stat-trader15-out.log",
            error_file: "/data/will/bnmm/stat-trader15-error.log",
        },
        {
            name: "stat_trader16",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader16"',
            out_file: "/data/will/bnmm/stat-trader16-out.log",
            error_file: "/data/will/bnmm/stat-trader16-error.log",
        },
        {
            name: "stat_trader17",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader17"',
            out_file: "/data/will/bnmm/stat-trader17-out.log",
            error_file: "/data/will/bnmm/stat-trader17-error.log",
        },
        {
            name: "stat_trader18",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader18"',
            out_file: "/data/will/bnmm/stat-trader18-out.log",
            error_file: "/data/will/bnmm/stat-trader18-error.log",
        },
        {
            name: "stat_spot_fbg005",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node spotstat.js --account fbg005"',
            out_file: "/data/will/bnsmm/stat-spot-fbg005-out.log",
            error_file: "/data/will/bnsmm/stat-spot-fbg005-error.log",
        },
    ],
};
