module.exports = {
    apps: [
        {
            name: "hedge",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 9 node hedge.js"',
            out_file: "/data/will/binance_utils/hedge-out.log",
            error_file: "/data/will/binance_utils/hedge-error.log",
        },
        {
            name: "monit_private_ips",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node monitPrivateIPs.js"',
            out_file: "/data/will/binance_utils/monit-private-ips-out.log",
            error_file: "/data/will/binance_utils/monit-private-ips-error.log",
        },
        {
            name: "monit_okx_ticker",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node monitOkxTicker.js"',
            out_file: "/data/will/binance_utils/monit-okx-ticker-out.log",
            error_file: "/data/will/binance_utils/monit-okx-ticker-error.log",
        },
        {
            name: "monit_okx_zoneb_ticker",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node monitOkxZoneBTicker.js"',
            out_file: "/data/will/binance_utils/monit-okx-zoneb-ticker-out.log",
            error_file:
                "/data/will/binance_utils/monit-okx-zoneb-ticker-error.log",
        },
        {
            name: "stat_btech001",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account btech001"',
            out_file: "/data/will/bnmm/stat-btech001-out.log",
            error_file: "/data/will/bnmm/stat-btech001-error.log",
        },
        {
            name: "stat_btech002",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account btech002"',
            out_file: "/data/will/bnmm/stat-btech002-out.log",
            error_file: "/data/will/bnmm/stat-btech002-error.log",
        },
        {
            name: "stat_btech003",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account btech003"',
            out_file: "/data/will/bnmm/stat-btech003-out.log",
            error_file: "/data/will/bnmm/stat-btech003-error.log",
        },
        {
            name: "stat_btech004",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account btech004"',
            out_file: "/data/will/bnmm/stat-btech004-out.log",
            error_file: "/data/will/bnmm/stat-btech004-error.log",
        },
        {
            name: "stat_elkdaphne1",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account elkdaphne1"',
            out_file: "/data/will/bnmm/stat-elkdaphne1-out.log",
            error_file: "/data/will/bnmm/stat-elkdaphne1-error.log",
        },
        {
            name: "stat_elkdaphne2",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account elkdaphne2"',
            out_file: "/data/will/bnmm/stat-elkdaphne2-out.log",
            error_file: "/data/will/bnmm/stat-elkdaphne2-error.log",
        },
        {
            name: "stat_elkdaphne3",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account elkdaphne3"',
            out_file: "/data/will/bnmm/stat-elkdaphne3-out.log",
            error_file: "/data/will/bnmm/stat-elkdaphne3-error.log",
        },
        {
            name: "stat_elkdaphne4",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account elkdaphne4"',
            out_file: "/data/will/bnmm/stat-elkdaphne4-out.log",
            error_file: "/data/will/bnmm/stat-elkdaphne4-error.log",
        },
        {
            name: "stat_fbg001",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account fbg001"',
            out_file: "/data/will/bnmm/stat-fbg001-out.log",
            error_file: "/data/will/bnmm/stat-fbg001-error.log",
        },
        {
            name: "stat_fbg002",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account fbg002"',
            out_file: "/data/will/bnmm/stat-fbg002-out.log",
            error_file: "/data/will/bnmm/stat-fbg002-error.log",
        },
        {
            name: "stat_fbg003",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account fbg003"',
            out_file: "/data/will/bnmm/stat-fbg003-out.log",
            error_file: "/data/will/bnmm/stat-fbg003-error.log",
        },
        {
            name: "stat_fbg004",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account fbg004"',
            out_file: "/data/will/bnmm/stat-fbg004-out.log",
            error_file: "/data/will/bnmm/stat-fbg004-error.log",
        },
        {
            name: "stat_trader1",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader1"',
            out_file: "/data/will/bnmm/stat-trader1-out.log",
            error_file: "/data/will/bnmm/stat-trader1-error.log",
        },
        {
            name: "stat_trader2",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader2"',
            out_file: "/data/will/bnmm/stat-trader2-out.log",
            error_file: "/data/will/bnmm/stat-trader2-error.log",
        },
        {
            name: "stat_trader3",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader3"',
            out_file: "/data/will/bnmm/stat-trader3-out.log",
            error_file: "/data/will/bnmm/stat-trader3-error.log",
        },
        {
            name: "stat_trader4",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader4"',
            out_file: "/data/will/bnmm/stat-trader4-out.log",
            error_file: "/data/will/bnmm/stat-trader4-error.log",
        },
        {
            name: "stat_trader6",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader6"',
            out_file: "/data/will/bnmm/stat-trader6-out.log",
            error_file: "/data/will/bnmm/stat-trader6-error.log",
        },
        {
            name: "stat_trader14",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader14"',
            out_file: "/data/will/bnmm/stat-trader14-out.log",
            error_file: "/data/will/bnmm/stat-trader14-error.log",
        },
        {
            name: "stat_trader15",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader15"',
            out_file: "/data/will/bnmm/stat-trader15-out.log",
            error_file: "/data/will/bnmm/stat-trader15-error.log",
        },
        {
            name: "stat_trader16",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader16"',
            out_file: "/data/will/bnmm/stat-trader16-out.log",
            error_file: "/data/will/bnmm/stat-trader16-error.log",
        },
        {
            name: "stat_trader17",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader17"',
            out_file: "/data/will/bnmm/stat-trader17-out.log",
            error_file: "/data/will/bnmm/stat-trader17-error.log",
        },
        {
            name: "stat_trader18",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node stat.js --account trader18"',
            out_file: "/data/will/bnmm/stat-trader18-out.log",
            error_file: "/data/will/bnmm/stat-trader18-error.log",
        },
        {
            name: "stat_spot_fbg005",
            script: "/usr/bin/bash",
            args: '-c "taskset -c 7 node spotstat.js --account fbg005"',
            out_file: "/data/will/bnsmm/stat-spot-fbg005-out.log",
            error_file: "/data/will/bnsmm/stat-spot-fbg005-error.log",
        },
    ],
};
